#!/usr/bin/env bash

# Get into docker shell
function de() {
  docker exec -i -t $@ /bin/bash
}

# Remove dangling docker images
function drmd() {
  docker rmi -f $(docker images -f "dangling=true" -q)
}

alias dp="docker ps"
alias dpa="docker ps -a"
alias di="docker images"
alias dia="docker images -a"
