#!/usr/bin/env bash

mnthal() (
  sudo mkdir -p /Users/Shared/halmount
  sudo mount -t nfs -o resvport,rw 192.168.0.18:/var/data/abhishek/ /Users/Shared/halmount
)

umnthal() {
  sudo umount -f /Users/Shared/halmount
}

alias hal="ssh abhishek@192.168.0.18"
