#!/usr/bin/env bash

# Convert *all* HEIF in a directory to JPG
#
# Download `heif-convert` and the `libheif-examples` toolset:
#   sudo apt install libheif-examples
#
# The official ubuntu version can be behind the custom version published by
# the repo owners: https://launchpad.net/~strukturag/+archive/ubuntu/libheif
#
# In particular, this issue was fixed in 1.19.x in late 2024 that's required
# for `tmap` images
# https://github.com/strukturag/libheif/issues/1190
#
# Install from PPA
#
# $ sudo add-apt-repository ppa:strukturag/libheif
# $ sudo add-apt-repository ppa:strukturag/libde265
# $ sudo apt update
# $ sudo apt install libheif-examples
function all_heif2jpg {
  YELLOW='\033[0;33m'
  NOCOLOR='\033[0m'

  for file in *.HEIC
  do 
    echo -e "${YELLOW}# $file${NOCOLOR}"

    basename=${file%.*}
    # -q 100 is lossless, but file size is huge
    # -q 80 is good enough for majority of display needs
    heif-convert -q 80 "$file" "$basename.JPG"

    # Sometimes the above outputs .JPG and sometimes .jpg
    # So account for both

    # Remove the depth files it generates
    [ -e "$basename-depth.JPG" ] && rm "$basename-depth.JPG"
    [ -e "$basename-depth.jpg" ] && rm "$basename-depth.jpg"

    # Set timestamp of new file to be timestamp of old file
    [ -e "$basename.JPG" ] && touch -r $file "$basename.JPG"
    [ -e "$basename.jpg" ] && touch -r $file "$basename.jpg"
  done

  echo "Extensions:"
  ls -q -U | awk -F . '{print $NF}' | sort | uniq -c | awk '{print $2,$1}'
}
