#!/usr/bin/env bash

alias kc="kubectl"
alias mku="minikube"

function kcls {
  echo -e "\033[1;33mkubectl get deployments,services,pods\033[0m"
  echo ""

  kubectl get deployments,services,pods
}

# Provide context on current kubernetes cluster + namespace
source "$SRC_DIR/scripts/kube_ps1"
function kubeami {
  kube_ps1
}
