#!/usr/bin/env bash

# === Postgres 14
#
# After upgrading postgres via homebrew:
#
#   brew services stop postgresql && pg-stop
#   rm -rf /usr/local/var/postgres*                      # Removes all old data
#   initdb --locale=C -E UTF-8 /usr/local/var/postgres   # Initialize new data folder
#   <Update version in commands below>
#   sbp
#   pg-start
#   /usr/local/opt/postgresql/bin/createuser -s postgres # Create new role/user
#
#   Log in with `psql -U postgres`
export PATH=$PATH://usr/local/opt/postgresql@14/bin
alias pg-start="pg_ctl -D /usr/local/var/postgres start"
alias pg-stop="pg_ctl -D /usr/local/var/postgres stop"

export PATH
