#!/usr/bin/env bash

# CallRail
export AWS_VAULT_KEYCHAIN_NAME=login

function ave() {
  aws-vault exec --duration=12h -- $@
}

function avl() {
  aws-vault login -- $@
}

function wfh() {
  ave cr-stage-dev bingo aws allow
  ave cr-prod-dev bingo aws allow
}

function api_get() {
  curl --silent -H "Authorization:Token token=1ffb9f763d218ead9761419800b71eb1" $1 | json_pp
}

alias staging-console="ave cr-stage-dev bingo ssm console callrail staging"
alias read-console="ave cr-prod-console bingo ssm read-console"
alias write-console="ave cr-prod-lead bingo ssm console callrail us-east-1 --role util"
alias aws-role="echo $AWS_VAULT"

# Specify with a port
# e.g. `nk 8000`
alias nk="~/Downloads/ngrok http --region=us --hostname=abhishek-callrail.ngrok.io"

function gh {
  if [ -d "$HOME/git/callrail/$1" ]; then
    cd $HOME/git/callrail/$1
  fi

  if [ -d "$HOME/git/abhishek/$1" ]; then
    cd $HOME/git/abhishek/$1
  fi
}

# Looky configuration
function looky_local() {
  yarn tools config set crDevHost callrail.test
  yarn tools config set crDevProtocol http
}

function looky_remote() {
  yarn tools config set crDevHost app.staging-callrail.com
  yarn tools config set crDevProtocol https
}

function looky_qa6() {
  yarn tools config set crDevHost mount-wario.qa-callrail.com
  yarn tools config set crDevProtocol https
}

function looky_namespace() {
  yarn tools config set crDevHost app.abhchand.eks.staging-callrail.com
  yarn tools config set crDevProtocol https
}

alias rp="touch tmp/restart.txt ; echo 'restarted pow server'"
alias cr="cd $HOME/git/callrail/callrail"
alias ghs="cd $HOME/git/abhishek/github-scripts"

# Kubernetes
alias wp="watch -n3 'kubectl get pods'"
alias wp-staging="watch -n3 'kubectl -n staging get pods | grep inti'"
alias wp-prod="watch -n3 'kubectl -n prod get pods | grep inti'"
alias goprod="kubectl config use-context prod"
alias godev="kubectl config use-context non-prod"
